const v=document.querySelector('#camera'),start=document.querySelector('#start'),manual=document.querySelector('#manual'),picker=document.querySelector('#picker'),exp=document.querySelector('#experience'),ret=document.querySelector('#reticle'),statusEl=document.querySelector('#status'),canvas=document.querySelector('#scan'),ctx=canvas.getContext('2d',{willReadFrequently:true}),mascot=document.querySelector('#mascot'),storyVisual=document.querySelector('#storyVisual'),storyCaption=document.querySelector('#storyCaption');
let stream=null,current=0,cvReady=false,targets=[],scanning=false,lastScan=0,lastCandidate=0,candidateHits=0,lastSeen=0,misses=0;const T=DELTAX_TRACKING;
const STORIES={
1:{move:'explore',caption:'Hay un valor invisible creciendo en los campos.',items:['SUELO','AGUA','CULTIVO','PRÁCTICAS'],kind:'discover'},
2:{move:'bridge',caption:'Convertimos datos dispersos en evidencia que abre oportunidades.',items:['DATOS','EVIDENCIA','OPORTUNIDADES'],kind:'route'},
3:{move:'connect',caption:'Conectamos personas, territorio y mercados.',items:['COOPERATIVAS','FAMILIAS','COMUNIDADES','COMPRADORES'],kind:'network'},
4:{move:'collect',caption:'La evidencia local se vuelve visible y llega al Marketplace DeltaX.',items:['EVIDENCIA LOCAL','MARKETPLACE DELTAX'],kind:'market'},
5:{move:'run',caption:'Lo aprendido en un territorio puede replicarse y crecer.',items:['TERRITORIO','REPLICAR','ESCALAR'],kind:'roads'},
6:{move:'pulse',caption:'Esto ya está ocurriendo.',items:['25 ORGANIZACIONES','1.721 PRODUCTORES','675 MUJERES','181 JÓVENES'],kind:'pulse'},
7:{move:'value',caption:'El valor ambiental encuentra un modelo de negocio.',items:['VALOR AMBIENTAL','MERCADO'],kind:'value'},
8:{move:'human',caption:'Detrás de cada dato hay agricultores, familias y una historia.',items:['SAN CARLOS DOS','PERSONAS','HISTORIA'],kind:'human'},
9:{move:'world',caption:'La evidencia viaja desde el campo hacia mercados en el mundo.',items:['EVIDENCIA','tCO₂e','CRÉDITO DE CARBONO','MARKETPLACE','MUNDO'],kind:'world'},
10:{move:'future',caption:'La siguiente etapa es ampliar las oportunidades.',items:['MÁS TERRITORIOS','MÁS AGRICULTORES','MÁS VALOR'],kind:'future'},
11:{move:'celebrate',caption:'Cada historia tiene un valor. DeltaX ayuda al mundo a descubrirlo.',items:['DELTAX','CADA HISTORIA TIENE UN VALOR'],kind:'final'}
};
function scene(n){const s=DELTAX_SCENES[n-1];if(!s)return;if(current===n&&exp.dataset.active==='1'){lastSeen=Date.now();return}current=n;lastSeen=Date.now();misses=0;exp.dataset.active='1';exp.classList.remove('hidden');ret.classList.add('hidden');document.querySelector('#sceneNo').textContent='LÁMINA '+n;document.querySelector('#sceneTitle').textContent=s.title;document.querySelector('#sceneSub').textContent=s.sub;document.querySelector('#flow').textContent='';statusEl.textContent='LÁMINA '+n+' RECONOCIDA';cinematic(n);particles()}
function cinematic(n){const st=STORIES[n];mascot.className='';mascot.id='mascot';void mascot.offsetWidth;mascot.classList.add('move-'+st.move);storyCaption.textContent=st.caption;storyVisual.className='story '+st.kind;storyVisual.innerHTML='';st.items.forEach((txt,i)=>{const el=document.createElement('span');el.className='story-node n'+(i+1);el.textContent=txt;el.style.setProperty('--i',i);storyVisual.appendChild(el)});if(['route','network','market','roads','world','future'].includes(st.kind)){for(let i=0;i<Math.max(1,st.items.length-1);i++){const line=document.createElement('i');line.className='story-line l'+(i+1);line.style.setProperty('--i',i);storyVisual.appendChild(line)}}}
function particles(){const p=document.querySelector('#particles');p.innerHTML='';for(let i=0;i<18;i++){const e=document.createElement('i');e.className='particle';e.style.left=(8+Math.random()*84)+'%';e.style.top=(25+Math.random()*50)+'%';e.style.animationDelay=(Math.random()*1.5)+'s';p.appendChild(e)}}
function hideScene(){if(!current)return;current=0;exp.dataset.active='0';exp.classList.add('hidden');ret.classList.remove('hidden')}
DELTAX_SCENES.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.onclick=()=>{picker.classList.add('hidden');scene(s.id)};picker.appendChild(b)});manual.onclick=()=>picker.classList.toggle('hidden');
function waitForCV(){if(window.cv&&cv.Mat){cvReady=true;statusEl.textContent='RECONOCIMIENTO LISTO';start.disabled=false;loadTargets();return}setTimeout(waitForCV,200)}waitForCV();
async function loadTargets(){statusEl.textContent='CARGANDO 11 LÁMINAS…';for(const t of T.targets){try{const img=await loadImage(t.src),c=document.createElement('canvas'),scale=Math.min(1,900/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const rgba=cv.imread(c),gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);const kp=new cv.KeyPointVector(),des=new cv.Mat(),mask=new cv.Mat(),orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);targets.push({scene:t.scene,des});rgba.delete();gray.delete();kp.delete();mask.delete();orb.delete()}catch(e){console.warn('target',t.scene,e)}}statusEl.textContent=`RECONOCIMIENTO LISTO · ${targets.length} LÁMINAS`}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});v.srcObject=stream;await v.play();start.style.display='none';statusEl.textContent='CÁMARA ACTIVA · BUSCANDO LÁMINA';requestAnimationFrame(loop)}catch(e){console.error(e);statusEl.textContent='NO SE PUDO ABRIR LA CÁMARA · USA MODO MANUAL'}};
function loop(ts){if(stream&&cvReady&&targets.length&&ts-lastScan>T.scanEveryMs&&!scanning){lastScan=ts;recognize()}requestAnimationFrame(loop)}
function recognize(){scanning=true;let rgba,gray,kp,des,mask,orb;try{const w=640,h=Math.max(320,Math.round(640*v.videoHeight/v.videoWidth));canvas.width=w;canvas.height=h;ctx.drawImage(v,0,0,w,h);rgba=cv.imread(canvas);gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);kp=new cv.KeyPointVector();des=new cv.Mat();mask=new cv.Mat();orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);if(des.rows<12){misses++;if(misses>4)hideScene();return}let scores=[];for(const t of targets){const matcher=new cv.BFMatcher(cv.NORM_HAMMING,true),matches=new cv.DMatchVector();matcher.match(t.des,des,matches);let good=0,sum=0;for(let i=0;i<matches.size();i++){const m=matches.get(i);if(m.distance<=T.matchDistance){good++;sum+=m.distance}}scores.push({scene:t.scene,good,avg:good?sum/good:999});matches.delete();matcher.delete()}scores.sort((a,b)=>b.good-a.good||a.avg-b.avg);const best=scores[0],second=scores[1]||{good:0};const decisive=best.good>=T.minGoodMatches&&best.good>=second.good+T.minLead;if(decisive){misses=0;if(lastCandidate===best.scene)candidateHits++;else{lastCandidate=best.scene;candidateHits=1}statusEl.textContent=`IDENTIFICANDO LÁMINA ${best.scene}…`;if(candidateHits>=T.confirmFrames){candidateHits=0;lastCandidate=0;scene(best.scene)}}else{candidateHits=0;lastCandidate=0;misses++;if(misses>4){hideScene();statusEl.textContent='CÁMARA ACTIVA · CENTRA LA LÁMINA'}}}catch(e){console.error(e);statusEl.textContent='RECONOCIMIENTO EN PAUSA · USA MODO MANUAL'}finally{[rgba,gray,kp,des,mask,orb].forEach(x=>{try{x&&x.delete&&x.delete()}catch(_){}});scanning=false}}
window.addEventListener('beforeunload',()=>{targets.forEach(t=>{try{t.des.delete()}catch(_){}});if(stream)stream.getTracks().forEach(t=>t.stop())});