const v=document.querySelector('#camera'),start=document.querySelector('#start'),manual=document.querySelector('#manual'),picker=document.querySelector('#picker'),exp=document.querySelector('#experience'),ret=document.querySelector('#reticle'),statusEl=document.querySelector('#status'),canvas=document.querySelector('#scan'),ctx=canvas.getContext('2d',{willReadFrequently:true});
let stream=null,current=0,cvReady=false,targets=[],scanning=false,lastScan=0,lastCandidate=0,candidateHits=0,sceneUntil=0;const T=DELTAX_TRACKING;
function scene(n){const s=DELTAX_SCENES[n-1];if(!s)return;current=n;sceneUntil=Date.now()+6500;exp.classList.remove('hidden');ret.classList.add('hidden');document.querySelector('#sceneNo').textContent='LÁMINA '+n;document.querySelector('#sceneTitle').textContent=s.title;document.querySelector('#sceneSub').textContent=s.sub;document.querySelector('#flow').textContent=s.action==='world'?'EVIDENCIA  →  tCO₂e  →  MARKETPLACE  →  MUNDO':'';statusEl.textContent='LÁMINA '+n+' RECONOCIDA';particles();setTimeout(()=>{if(Date.now()>=sceneUntil){exp.classList.add('hidden');ret.classList.remove('hidden');statusEl.textContent='CÁMARA ACTIVA · BUSCANDO LÁMINA'}},6600)}
function particles(){const p=document.querySelector('#particles');p.innerHTML='';for(let i=0;i<14;i++){const e=document.createElement('i');e.className='particle';e.style.left=(15+Math.random()*70)+'%';e.style.top=(35+Math.random()*35)+'%';e.style.animationDelay=(Math.random()*1.5)+'s';p.appendChild(e)}}
DELTAX_SCENES.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.onclick=()=>{picker.classList.add('hidden');scene(s.id)};picker.appendChild(b)});manual.onclick=()=>picker.classList.toggle('hidden');
function waitForCV(){if(window.cv&&cv.Mat){cvReady=true;statusEl.textContent='RECONOCIMIENTO LISTO';start.disabled=false;loadTargets();return}setTimeout(waitForCV,200)}waitForCV();
async function loadTargets(){statusEl.textContent='CARGANDO 11 LÁMINAS…';for(const t of T.targets){try{const img=await loadImage(t.src),c=document.createElement('canvas'),scale=Math.min(1,900/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const rgba=cv.imread(c),gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);const kp=new cv.KeyPointVector(),des=new cv.Mat(),mask=new cv.Mat(),orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);targets.push({scene:t.scene,des});rgba.delete();gray.delete();kp.delete();mask.delete();orb.delete()}catch(e){console.warn('target',t.scene,e)}}statusEl.textContent=`RECONOCIMIENTO LISTO · ${targets.length} LÁMINAS`}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});v.srcObject=stream;await v.play();start.style.display='none';statusEl.textContent='CÁMARA ACTIVA · BUSCANDO LÁMINA';requestAnimationFrame(loop)}catch(e){console.error(e);statusEl.textContent='NO SE PUDO ABRIR LA CÁMARA · USA MODO MANUAL'}};
function loop(ts){if(stream&&cvReady&&targets.length&&ts-lastScan>T.scanEveryMs&&!scanning&&Date.now()>sceneUntil){lastScan=ts;recognize()}requestAnimationFrame(loop)}
function recognize(){scanning=true;let rgba,gray,kp,des,mask,orb;try{const w=640,h=Math.max(320,Math.round(640*v.videoHeight/v.videoWidth));canvas.width=w;canvas.height=h;ctx.drawImage(v,0,0,w,h);rgba=cv.imread(canvas);gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);kp=new cv.KeyPointVector();des=new cv.Mat();mask=new cv.Mat();orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);if(des.rows<12){statusEl.textContent='ACÉRCATE A LA LÁMINA';return}let best={scene:0,good:0,avg:999};for(const t of targets){const matcher=new cv.BFMatcher(cv.NORM_HAMMING,true),matches=new cv.DMatchVector();matcher.match(t.des,des,matches);let good=0,sum=0;for(let i=0;i<matches.size();i++){const m=matches.get(i);if(m.distance<=T.matchDistance){good++;sum+=m.distance}}const avg=good?sum/good:999;if(good>best.good||(good===best.good&&avg<best.avg))best={scene:t.scene,good,avg};matches.delete();matcher.delete()}if(best.good>=T.minGoodMatches){if(lastCandidate===best.scene)candidateHits++;else{lastCandidate=best.scene;candidateHits=1}statusEl.textContent=`IDENTIFICANDO LÁMINA ${best.scene}…`;if(candidateHits>=T.confirmFrames){candidateHits=0;lastCandidate=0;scene(best.scene)}}else{candidateHits=0;lastCandidate=0;statusEl.textContent='CÁMARA ACTIVA · CENTRA LA LÁMINA'}}catch(e){console.error(e);statusEl.textContent='RECONOCIMIENTO EN PAUSA · USA MODO MANUAL'}finally{[rgba,gray,kp,des,mask,orb].forEach(x=>{try{x&&x.delete&&x.delete()}catch(_){}});scanning=false}}
window.addEventListener('beforeunload',()=>{targets.forEach(t=>{try{t.des.delete()}catch(_){}});if(stream)stream.getTracks().forEach(t=>t.stop())});