const v=document.querySelector('#camera'),start=document.querySelector('#start'),manual=document.querySelector('#manual'),picker=document.querySelector('#picker'),exp=document.querySelector('#experience'),ret=document.querySelector('#reticle'),statusEl=document.querySelector('#status'),canvas=document.querySelector('#scan'),ctx=canvas.getContext('2d',{willReadFrequently:true}),mascot=document.querySelector('#mascot'),storyVisual=document.querySelector('#storyVisual'),storyCaption=document.querySelector('#storyCaption'),photoBtn=document.querySelector('#photo'),recordBtn=document.querySelector('#record'),captureControls=document.querySelector('#captureControls'),captureCanvas=document.querySelector('#captureCanvas'),captureNotice=document.querySelector('#captureNotice');
let stream=null,current=0,cvReady=false,targets=[],scanning=false,lastScan=0,lastCandidate=0,candidateHits=0,misses=0,recorder=null,recordChunks=[],captureRAF=0,birdPaused=false,birdActionTimer=0;const T=DELTAX_TRACKING;
const STORIES={1:{move:'explore',items:['SUELO','AGUA','CULTIVO','PRÁCTICAS'],kind:'discover'},2:{move:'bridge',items:['ESFUERZO','DISTANCIA','OPORTUNIDADES'],kind:'route'},3:{move:'connect',items:['COOPERATIVAS','FAMILIAS','COMUNIDADES','COMPRADORES'],kind:'network'},4:{move:'collect',items:['EVIDENCIA LOCAL','MARKETPLACE DELTAX'],kind:'market'},5:{move:'run',items:['TERRITORIO','REPLICAR','ESCALAR'],kind:'roads'},6:{move:'pulse',items:['25 ORGANIZACIONES','1.721 PRODUCTORES','675 MUJERES','181 JÓVENES'],kind:'pulse'},7:{move:'value',items:['VALOR AMBIENTAL','MERCADO'],kind:'value'},8:{move:'human',items:['SAN CARLOS DOS','AGRICULTORES','FAMILIAS'],kind:'human'},9:{move:'world',items:['EXPEDIENTES','tCO₂e','BONOS','MARKETPLACE','MUNDO'],kind:'world'},10:{move:'future',items:['AGRICULTORES','FAMILIAS','ORGANIZACIONES'],kind:'future'},11:{move:'celebrate',items:['DELTAX','CADA HISTORIA TIENE UN VALOR'],kind:'final'}};
function scene(n){const s=DELTAX_SCENES[n-1];if(!s)return;if(current===n&&exp.dataset.active==='1')return;current=n;misses=0;exp.dataset.active='1';exp.classList.remove('hidden');ret.classList.add('hidden');document.querySelector('#sceneNo').textContent='LÁMINA '+n;document.querySelector('#sceneTitle').textContent=s.title;document.querySelector('#sceneSub').textContent=s.sub;document.querySelector('#flow').textContent=s.message||'';statusEl.textContent='LÁMINA '+n+' RECONOCIDA';cinematic(n);particles()}
function cinematic(n){const s=DELTAX_SCENES[n-1],st=STORIES[n];birdPaused=false;clearTimeout(birdActionTimer);mascot.className='bird-alive';void mascot.offsetWidth;mascot.classList.add('move-'+st.move,'bird-state-'+(n===8?'listen':n===11?'celebrate':'guide'));storyCaption.textContent=s.message||s.title;storyVisual.className='story '+st.kind;storyVisual.innerHTML='';st.items.forEach((txt,i)=>{const el=document.createElement('span');el.className='story-node n'+(i+1);el.textContent=txt;el.style.setProperty('--i',i);storyVisual.appendChild(el)});if(['route','network','market','roads','world','future'].includes(st.kind)){for(let i=0;i<Math.max(1,st.items.length-1);i++){const line=document.createElement('i');line.className='story-line l'+(i+1);line.style.setProperty('--i',i);storyVisual.appendChild(line)}}}
function birdSpecial(){if(!current)return;clearTimeout(birdActionTimer);mascot.classList.remove('bird-special','bird-paused');void mascot.offsetWidth;mascot.classList.add('bird-special');particles();birdActionTimer=setTimeout(()=>mascot.classList.remove('bird-special'),1800)}
function birdTogglePause(){if(!current)return;birdPaused=!birdPaused;mascot.classList.toggle('bird-paused',birdPaused);notice(birdPaused?'TOROGOZ EN PAUSA':'TOROGOZ ACTIVO')}
mascot.addEventListener('click',e=>{e.stopPropagation();birdSpecial()});mascot.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();birdSpecial()}});let birdPress=0;mascot.addEventListener('pointerdown',()=>{birdPress=setTimeout(birdTogglePause,650)});['pointerup','pointercancel','pointerleave'].forEach(ev=>mascot.addEventListener(ev,()=>clearTimeout(birdPress)));
window.addEventListener('deviceorientation',e=>{if(!current||birdPaused||e.gamma==null)return;const x=Math.max(-1,Math.min(1,e.gamma/35)),y=Math.max(-1,Math.min(1,(e.beta-45)/45));mascot.style.setProperty('--tiltX',(x*9)+'px');mascot.style.setProperty('--tiltY',(y*5)+'px');mascot.style.setProperty('--tiltR',(x*2.5)+'deg')},{passive:true});
function particles(){const p=document.querySelector('#particles');p.innerHTML='';for(let i=0;i<18;i++){const e=document.createElement('i');e.className='particle';e.style.left=(8+Math.random()*84)+'%';e.style.top=(25+Math.random()*50)+'%';e.style.animationDelay=(Math.random()*1.5)+'s';p.appendChild(e)}}
function hideScene(){if(!current)return;current=0;exp.dataset.active='0';exp.classList.add('hidden');ret.classList.remove('hidden')}
DELTAX_SCENES.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.onclick=()=>{picker.classList.add('hidden');scene(s.id)};picker.appendChild(b)});manual.onclick=()=>picker.classList.toggle('hidden');
function waitForCV(){if(window.cv&&cv.Mat){cvReady=true;statusEl.textContent='RECONOCIMIENTO LISTO';start.disabled=false;loadTargets();return}setTimeout(waitForCV,200)}waitForCV();
async function loadTargets(){statusEl.textContent='CARGANDO 11 LÁMINAS…';for(const t of T.targets){try{const img=await loadImage(t.src),c=document.createElement('canvas'),scale=Math.min(1,1000/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const rgba=cv.imread(c),gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);const kp=new cv.KeyPointVector(),des=new cv.Mat(),mask=new cv.Mat(),orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);targets.push({scene:t.scene,des});rgba.delete();gray.delete();kp.delete();mask.delete();orb.delete()}catch(e){console.warn('target',t.scene,e)}}statusEl.textContent=`RECONOCIMIENTO LISTO · ${targets.length} LÁMINAS`}
function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src+'?v=9'})}
start.onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});v.srcObject=stream;await v.play();start.style.display='none';captureControls.classList.remove('hidden');statusEl.textContent='CÁMARA ACTIVA · BUSCANDO LÁMINA';requestAnimationFrame(loop)}catch(e){console.error(e);statusEl.textContent='NO SE PUDO ABRIR LA CÁMARA · USA MODO MANUAL'}};
function loop(ts){if(stream&&cvReady&&targets.length&&ts-lastScan>T.scanEveryMs&&!scanning){lastScan=ts;recognize()}requestAnimationFrame(loop)}
function recognize(){scanning=true;let rgba,gray,kp,des,mask,orb;try{const w=640,h=Math.max(320,Math.round(640*v.videoHeight/v.videoWidth));canvas.width=w;canvas.height=h;ctx.drawImage(v,0,0,w,h);rgba=cv.imread(canvas);gray=new cv.Mat();cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);kp=new cv.KeyPointVector();des=new cv.Mat();mask=new cv.Mat();orb=new cv.ORB(T.maxFeatures);orb.detectAndCompute(gray,mask,kp,des);if(des.rows<15){misses++;if(misses>5)hideScene();return}let scores=[];for(const t of targets){const matcher=new cv.BFMatcher(cv.NORM_HAMMING,true),matches=new cv.DMatchVector();matcher.match(t.des,des,matches);let good=0,sum=0;for(let i=0;i<matches.size();i++){const m=matches.get(i);if(m.distance<=T.matchDistance){good++;sum+=m.distance}}scores.push({scene:t.scene,good,avg:good?sum/good:999});matches.delete();matcher.delete()}scores.sort((a,b)=>b.good-a.good||a.avg-b.avg);const best=scores[0],second=scores[1]||{good:0};const decisive=best.good>=T.minGoodMatches&&best.good>=second.good+T.minLead;if(decisive){misses=0;if(lastCandidate===best.scene)candidateHits++;else{lastCandidate=best.scene;candidateHits=1}statusEl.textContent=`IDENTIFICANDO LÁMINA ${best.scene}…`;if(candidateHits>=T.confirmFrames){candidateHits=0;lastCandidate=0;scene(best.scene)}}else{candidateHits=0;lastCandidate=0;misses++;if(misses>5){hideScene();statusEl.textContent='CÁMARA ACTIVA · CENTRA LA LÁMINA'}}}catch(e){console.error(e);statusEl.textContent='RECONOCIMIENTO EN PAUSA · USA MODO MANUAL'}finally{[rgba,gray,kp,des,mask,orb].forEach(x=>{try{x&&x.delete&&x.delete()}catch(_){}});scanning=false}}
function fitCapture(){const dpr=Math.min(2,window.devicePixelRatio||1),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(captureCanvas.width!==w||captureCanvas.height!==h){captureCanvas.width=w;captureCanvas.height=h}return dpr}
function drawCapture(){const dpr=fitCapture(),c=captureCanvas.getContext('2d'),W=captureCanvas.width,H=captureCanvas.height;c.clearRect(0,0,W,H);const vw=v.videoWidth||1280,vh=v.videoHeight||720,scale=Math.max(W/vw,H/vh),sw=W/scale,sh=H/scale,sx=(vw-sw)/2,sy=(vh-sh)/2;c.drawImage(v,sx,sy,sw,sh,0,0,W,H);c.save();c.scale(dpr,dpr);drawAR(c);c.restore()}
function drawAR(c){const W=innerWidth,H=innerHeight;c.fillStyle='rgba(0,0,0,.58)';c.fillRect(0,0,W,Math.min(H*.27,235));c.fillStyle='#f4d44d';c.font='900 26px Arial';c.fillText('ΔX DELTAX',9,32);c.font='900 10px Arial';c.fillText('ClimateTech · Agricultura · Bonos de Carbono',9,47);c.fillStyle='#fff';c.font='700 8px Arial';wrap(c,'Tecnología para medir, demostrar y dar valor al impacto ambiental.',9,60,W*.82,10);if(current){const s=DELTAX_SCENES[current-1];c.fillStyle='rgba(17,17,15,.84)';roundRect(c,18,H-130,W-36,100,10);c.fillStyle='#f4d44d';c.font='800 7px Arial';c.fillText('LÁMINA '+current,28,H-112);c.fillStyle='#fff';c.font='900 13px Arial';wrap(c,s.title,28,H-94,W-56,15);c.font='500 8px Arial';wrap(c,s.sub,28,H-65,W-56,10);c.fillStyle='#f4d44d';c.font='900 9px Arial';wrap(c,s.message||'',28,H-42,W-56,10);const img=mascot.querySelector('img');if(img&&img.complete){const r=mascot.getBoundingClientRect();c.drawImage(img,r.left,r.top,r.width,r.height)}}}
function roundRect(c,x,y,w,h,r){c.beginPath();c.roundRect?c.roundRect(x,y,w,h,r):(c.rect(x,y,w,h));c.fill()}
function wrap(c,text,x,y,maxWidth,lineHeight){if(!text)return;const words=text.split(' ');let line='',yy=y;for(const word of words){const test=line+word+' ';if(c.measureText(test).width>maxWidth&&line){c.fillText(line,x,yy);line=word+' ';yy+=lineHeight}else line=test}c.fillText(line,x,yy)}
function notice(t){captureNotice.textContent=t;captureNotice.classList.remove('hidden');setTimeout(()=>captureNotice.classList.add('hidden'),2200)}
function downloadBlob(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
photoBtn.onclick=()=>{if(!stream)return;drawCapture();captureCanvas.toBlob(blob=>{if(!blob)return;downloadBlob(blob,'DeltaX-AR-'+Date.now()+'.jpg');notice('FOTO AR GUARDADA')},'image/jpeg',.94)};
recordBtn.onclick=()=>{if(!stream)return;if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!window.MediaRecorder||!captureCanvas.captureStream){notice('VIDEO NO COMPATIBLE EN ESTE NAVEGADOR');return}recordChunks=[];const out=captureCanvas.captureStream(30);let mime='';for(const m of ['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm']){if(MediaRecorder.isTypeSupported(m)){mime=m;break}}try{recorder=new MediaRecorder(out,mime?{mimeType:mime}:undefined)}catch(e){notice('NO SE PUDO INICIAR VIDEO');return}recorder.ondataavailable=e=>{if(e.data&&e.data.size)recordChunks.push(e.data)};recorder.onstop=()=>{cancelAnimationFrame(captureRAF);const blob=new Blob(recordChunks,{type:recorder.mimeType||'video/webm'});downloadBlob(blob,'DeltaX-AR-'+Date.now()+'.webm');recordBtn.classList.remove('recording');recordBtn.querySelector('span').textContent='VIDEO';notice('VIDEO AR GUARDADO')};const captureLoop=()=>{drawCapture();captureRAF=requestAnimationFrame(captureLoop)};captureLoop();recorder.start(500);recordBtn.classList.add('recording');recordBtn.querySelector('span').textContent='DETENER';notice('GRABANDO REALIDAD AUMENTADA')};
window.addEventListener('beforeunload',()=>{targets.forEach(t=>{try{t.des.delete()}catch(_){}});if(stream)stream.getTracks().forEach(t=>t.stop());if(captureRAF)cancelAnimationFrame(captureRAF)});