const $=s=>document.querySelector(s);const app=$('#app'),video=$('#camera'),scan=$('#scan'),ctx=scan.getContext('2d',{willReadFrequently:true}),start=$('#start'),manual=$('#manual'),picker=$('#picker'),statusEl=$('#status'),instruction=$('#instruction'),badge=$('#recognitionBadge'),sceneBox=$('#sceneOverlay'),photo=$('#photo'),record=$('#record'),capture=$('#captureCanvas'),noticeEl=$('#captureNotice');let stream=null,cvReady=false,targets=[],scanning=false,lastScan=0,current=0,lastCandidate=0,hits=0,recorder=null,chunks=[],raf=0;const T=window.DELTAX_TRACKING;
function state(s){app.dataset.state=s;if(s==='welcome'){instruction.textContent='Activa la cámara para comenzar';start.querySelector('b').textContent='ACTIVAR CÁMARA'}else{instruction.textContent='Mantén la lámina en el cuadro';start.querySelector('b').textContent='DESACTIVAR CÁMARA'}}
function msg(t){noticeEl.textContent=t;noticeEl.classList.remove('hidden');setTimeout(()=>noticeEl.classList.add('hidden'),1800)}
function waitCV(){if(window.cv&&cv.Mat){cvReady=true;start.disabled=false;statusEl.textContent='Cargando 11 láminas…';loadTargets()}else setTimeout(waitCV,200)}waitCV();
function loadImage(src){return new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src+'?v=2'})}
async function loadTargets(){for(const t of T.targets){try{const img=await loadImage(t.src),c=document.createElement('canvas'),scale=Math.min(1,900/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);const rgba=cv.imread(c),gray=new cv.Mat(),kp=new cv.KeyPointVector(),des=new cv.Mat(),mask=new cv.Mat(),orb=new cv.ORB(T.maxFeatures);cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);orb.detectAndCompute(gray,mask,kp,des);targets.push({scene:t.scene,des});[rgba,gray,kp,mask,orb].forEach(x=>x.delete())}catch(e){console.warn(e)}}statusEl.textContent='Reconocimiento listo · '+targets.length+' láminas'}
async function cameraOn(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();state('camera');statusEl.textContent='Cámara activa · buscando lámina';requestAnimationFrame(loop)}catch(e){statusEl.textContent='No se pudo abrir la cámara';msg('USA MODO MANUAL')}}
function cameraOff(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}video.srcObject=null;current=0;sceneBox.classList.add('hidden');badge.style.display='';state('welcome');statusEl.textContent='Cámara desactivada'}
start.onclick=()=>stream?cameraOff():cameraOn();
window.DELTAX_SCENES.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.onclick=()=>{picker.classList.add('hidden');showScene(s.id)};picker.appendChild(b)});manual.onclick=()=>picker.classList.toggle('hidden');
function showScene(n){const s=DELTAX_SCENES[n-1];if(!s)return;current=n;$('#sceneNo').textContent='LÁMINA '+n;$('#sceneTitle').textContent=s.title;$('#sceneSub').textContent=s.sub;$('#flow').textContent=s.message||'';sceneBox.classList.remove('hidden');state('recognized');badge.textContent='✓ ¡LÁMINA '+n+' RECONOCIDA!';statusEl.textContent='Lámina '+n+' reconocida'}
function loop(ts){if(stream&&cvReady&&targets.length&&!scanning&&ts-lastScan>Math.max(450,T.scanEveryMs||450)){lastScan=ts;recognize()}if(stream)requestAnimationFrame(loop)}
function recognize(){scanning=true;let rgba,gray,kp,des,mask,orb;try{const w=640,h=Math.max(320,Math.round(w*(video.videoHeight||720)/(video.videoWidth||1280)));scan.width=w;scan.height=h;ctx.drawImage(video,0,0,w,h);rgba=cv.imread(scan);gray=new cv.Mat();kp=new cv.KeyPointVector();des=new cv.Mat();mask=new cv.Mat();orb=new cv.ORB(T.maxFeatures);cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);orb.detectAndCompute(gray,mask,kp,des);if(des.rows<18)return;const scores=[];for(const t of targets){const matcher=new cv.BFMatcher(cv.NORM_HAMMING,true),m=new cv.DMatchVector();matcher.match(t.des,des,m);let good=0,sum=0;for(let i=0;i<m.size();i++){const x=m.get(i);if(x.distance<=T.matchDistance){good++;sum+=x.distance}}scores.push({scene:t.scene,good,avg:good?sum/good:999});m.delete();matcher.delete()}scores.sort((a,b)=>b.good-a.good||a.avg-b.avg);const a=scores[0],b=scores[1]||{good:0};if(a.good>=T.minGoodMatches&&a.good>=b.good+T.minLead){if(lastCandidate===a.scene)hits++;else{lastCandidate=a.scene;hits=1}statusEl.textContent='Identificando lámina…';if(hits>=3){hits=0;lastCandidate=0;showScene(a.scene)}}else{hits=0;lastCandidate=0;if(current){current=0;sceneBox.classList.add('hidden');state('camera')}statusEl.textContent='Cámara activa · buscando lámina'}}catch(e){console.error(e)}finally{[rgba,gray,kp,des,mask,orb].forEach(x=>{try{x&&x.delete()}catch(_){}});scanning=false}}
function captureFrame(){const dpr=Math.min(2,devicePixelRatio||1),W=Math.round(innerWidth*dpr),H=Math.round(innerHeight*dpr);capture.width=W;capture.height=H;const c=capture.getContext('2d'),vw=video.videoWidth||1280,vh=video.videoHeight||720,scale=Math.max(W/vw,H/vh),sw=W/scale,sh=H/scale;c.drawImage(video,(vw-sw)/2,(vh-sh)/2,sw,sh,0,0,W,H);c.save();c.scale(dpr,dpr);c.fillStyle='rgba(0,0,0,.48)';c.fillRect(0,0,innerWidth,92);c.fillStyle='#fff';c.font='900 28px Arial';c.fillText('ΔX DELTAX',18,38);c.fillStyle='#f4d44d';c.font='900 11px Arial';c.fillText('Descubre el valor invisible',18,58);if(current){const s=DELTAX_SCENES[current-1];c.fillStyle='rgba(6,21,13,.84)';c.fillRect(18,innerHeight-150,innerWidth-36,112);c.fillStyle='#f4d44d';c.font='900 10px Arial';c.fillText('LÁMINA '+current,30,innerHeight-128);c.fillStyle='#fff';c.font='900 14px Arial';c.fillText(s.title.slice(0,42),30,innerHeight-106);c.font='700 10px Arial';c.fillText((s.message||'').slice(0,55),30,innerHeight-82)}c.restore()}
photo.onclick=()=>{if(!stream){msg('ACTIVA LA CÁMARA');return}captureFrame();capture.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DeltaX-AR-'+Date.now()+'.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);msg('FOTO AR GUARDADA')},'image/jpeg',.94)};
record.onclick=()=>{if(!stream){msg('ACTIVA LA CÁMARA');return}if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!window.MediaRecorder||!capture.captureStream){msg('VIDEO NO COMPATIBLE');return}chunks=[];const out=capture.captureStream(30);recorder=new MediaRecorder(out);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{cancelAnimationFrame(raf);const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='DeltaX-AR-'+Date.now()+'.webm';a.click();record.classList.remove('recording');record.querySelector('b').textContent='Video';msg('VIDEO AR GUARDADO')};const draw=()=>{captureFrame();raf=requestAnimationFrame(draw)};draw();recorder.start(500);record.classList.add('recording');record.querySelector('b').textContent='Detener';msg('GRABANDO')};
window.addEventListener('beforeunload',()=>{if(stream)stream.getTracks().forEach(t=>t.stop());targets.forEach(t=>{try{t.des.delete()}catch(_){}})});