const $=s=>document.querySelector(s),video=$('#camera'),start=$('#start'),screen=$('#startScreen'),statusEl=$('#status'),ret=$('#reticle'),scanText=$('#scanText'),ar=$('#ar'),bird=$('#bird'),picker=$('#picker'),photo=$('#photo'),record=$('#record'),flip=$('#flip'),manual=$('#manual'),scan=$('#scan'),sctx=scan.getContext('2d',{willReadFrequently:true}),capture=$('#capture');
let stream,current=0,facing='environment',targets=[],cvReady=false,lastScan=0,busy=false,candidate=0,hits=0,misses=0,recorder,chunks=[],raf=0;const T=DX_TRACK;
DX_SCENES.forEach(s=>{const b=document.createElement('button');b.textContent=s.id;b.onclick=()=>{picker.hidden=true;showScene(s.id)};picker.appendChild(b)});manual.onclick=()=>picker.hidden=!picker.hidden;
function showScene(id){const s=DX_SCENES[id-1];if(!s)return;current=id;misses=0;$('#sceneNo').textContent='LÁMINA '+id;$('#title').textContent=s.title;$('#sub').textContent=s.sub;$('#message').textContent=s.message;bird.dataset.action=s.action;bird.style.animation='none';void bird.offsetWidth;bird.style.animation='';ret.hidden=true;ar.hidden=false}
function hideScene(){current=0;ar.hidden=true;ret.hidden=false;scanText.textContent='APUNTA A UNA LÁMINA DELTAX'}
function waitCV(){if(window.cv&&cv.Mat){cvReady=true;statusEl.textContent='Cargando las 11 láminas…';loadTargets();return}setTimeout(waitCV,200)}waitCV();
const img=src=>new Promise((ok,no)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=no;i.src=src+'?v=18'});
async function loadTargets(){for(const t of T.targets){try{const im=await img(t.src),c=document.createElement('canvas'),scale=Math.min(1,1000/im.width);c.width=im.width*scale;c.height=im.height*scale;c.getContext('2d').drawImage(im,0,0,c.width,c.height);const rgba=cv.imread(c),gray=new cv.Mat,des=new cv.Mat,kp=new cv.KeyPointVector,mask=new cv.Mat,orb=new cv.ORB(T.maxFeatures);cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);orb.detectAndCompute(gray,mask,kp,des);targets.push({scene:t.scene,des});[rgba,gray,kp,mask,orb].forEach(x=>x.delete())}catch(e){console.warn(e)}}statusEl.textContent=`Reconocimiento listo · ${targets.length}/11 láminas`;start.disabled=!targets.length}
async function camera(mode=facing){if(stream)stream.getTracks().forEach(t=>t.stop());facing=mode;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080}},audio:true});video.srcObject=stream;video.classList.toggle('selfie',facing==='user');await video.play()}
start.onclick=async()=>{try{await camera();screen.style.display='none';requestAnimationFrame(loop)}catch(e){statusEl.textContent='No se pudo abrir la cámara'}};
flip.onclick=async()=>{try{await camera(facing==='environment'?'user':'environment');flip.querySelector('span').textContent=facing==='user'?'TRASERA':'SELFIE';if(facing==='user'){hideScene();scanText.textContent='MODO SELFIE · FOTO O VIDEO CON DELTAX'}else scanText.textContent='APUNTA A UNA LÁMINA DELTAX'}catch(e){console.error(e)}};
function loop(ts){if(stream&&facing==='environment'&&cvReady&&targets.length&&ts-lastScan>T.interval&&!busy){lastScan=ts;recognize()}requestAnimationFrame(loop)}
function recognize(){busy=true;let rgba,gray,des,kp,mask,orb;try{const w=640,h=Math.max(320,Math.round(w*(video.videoHeight||720)/(video.videoWidth||1280)));scan.width=w;scan.height=h;sctx.drawImage(video,0,0,w,h);rgba=cv.imread(scan);gray=new cv.Mat;des=new cv.Mat;kp=new cv.KeyPointVector;mask=new cv.Mat;orb=new cv.ORB(T.maxFeatures);cv.cvtColor(rgba,gray,cv.COLOR_RGBA2GRAY);orb.detectAndCompute(gray,mask,kp,des);if(des.rows<12){misses++;return}const scores=[];for(const t of targets){const m=new cv.BFMatcher(cv.NORM_HAMMING,true),v=new cv.DMatchVector;m.match(t.des,des,v);let good=0;for(let i=0;i<v.size();i++)if(v.get(i).distance<=T.matchDistance)good++;scores.push({scene:t.scene,good});v.delete();m.delete()}scores.sort((a,b)=>b.good-a.good);const a=scores[0],b=scores[1]||{good:0};if(a.good>=T.minGood&&a.good>=b.good+T.minLead){misses=0;if(candidate===a.scene)hits++;else{candidate=a.scene;hits=1}scanText.textContent='IDENTIFICANDO LÁMINA…';if(hits>=T.confirm){candidate=0;hits=0;showScene(a.scene)}}else{candidate=hits=0;misses++;if(misses>6)hideScene()}}catch(e){console.error(e)}finally{[rgba,gray,des,kp,mask,orb].forEach(x=>{try{x&&x.delete()}catch(_){}});busy=false}}
function draw(){const d=Math.min(2,devicePixelRatio||1),W=innerWidth*d,H=innerHeight*d;capture.width=W;capture.height=H;const c=capture.getContext('2d'),vw=video.videoWidth||1280,vh=video.videoHeight||720,scale=Math.max(W/vw,H/vh),sw=W/scale,sh=H/scale,sx=(vw-sw)/2,sy=(vh-sh)/2;c.save();if(facing==='user'){c.translate(W,0);c.scale(-1,1)}c.drawImage(video,sx,sy,sw,sh,0,0,W,H);c.restore();c.scale(d,d);c.fillStyle='rgba(10,10,8,.72)';c.fillRect(0,0,innerWidth,62);c.fillStyle='#f4d44d';c.font='900 28px Arial';c.fillText('ΔX',14,36);c.fillStyle='#fff';c.font='900 18px Arial';c.fillText('DeltaX',58,34);if(current){const s=DX_SCENES[current-1];c.fillStyle='rgba(10,10,8,.78)';c.fillRect(14,innerHeight-145,innerWidth-28,112);c.fillStyle='#f4d44d';c.font='900 11px Arial';c.fillText('LÁMINA '+current,25,innerHeight-122);c.fillStyle='#fff';c.font='900 15px Arial';c.fillText(s.title.slice(0,38),25,innerHeight-99);c.font='700 10px Arial';c.fillStyle='#f4d44d';c.fillText(s.message.slice(0,58),25,innerHeight-72);const bi=bird.querySelector('img');if(bi.complete){const r=bird.getBoundingClientRect();c.drawImage(bi,r.left,r.top,r.width,r.height)}}}
function save(blob,name){const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}photo.onclick=()=>{if(!stream)return;draw();capture.toBlob(b=>b&&save(b,'DeltaX-'+Date.now()+'.jpg'),'image/jpeg',.94)};
record.onclick=()=>{if(!stream)return;if(recorder&&recorder.state==='recording'){recorder.stop();return}if(!MediaRecorder||!capture.captureStream)return;chunks=[];const cs=capture.captureStream(30),audio=stream.getAudioTracks()[0];if(audio)cs.addTrack(audio);let mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm'].find(MediaRecorder.isTypeSupported.bind(MediaRecorder))||'';recorder=new MediaRecorder(cs,mime?{mimeType:mime}:undefined);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=()=>{cancelAnimationFrame(raf);record.classList.remove('recording');record.querySelector('span').textContent='VIDEO';save(new Blob(chunks,{type:recorder.mimeType}),'DeltaX-'+Date.now()+'.webm')};const frame=()=>{draw();raf=requestAnimationFrame(frame)};frame();recorder.start(500);record.classList.add('recording');record.querySelector('span').textContent='DETENER'};
addEventListener('pagehide',()=>{if(stream)stream.getTracks().forEach(t=>t.stop());targets.forEach(t=>t.des.delete())});