window.DX_SCENES=[
{id:1,title:'',sub:'',message:'',action:'discover'},
{id:2,title:'',sub:'',message:'',action:'bridge'},
{id:3,title:'',sub:'',message:'',action:'connect'},
{id:4,title:'',sub:'',message:'',action:'market'},
{id:5,title:'',sub:'',message:'',action:'expand'},
{id:6,title:'',sub:'',message:'',action:'pulse'},
{id:7,title:'',sub:'',message:'',action:'final'}];
window.DX_TRACK={targets:DX_SCENES.map(s=>({scene:s.id,src:`../assets/markers/lamina${String(s.id).padStart(2,'0')}.jpg`})),maxFeatures:1400,matchDistance:45,minGood:22,minLead:6,confirm:3,interval:360};